{"timestamp": "2025-10-02T12:01:19.486373+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "68 changes detected"}
{"timestamp": "2025-10-02T12:01:20.498081+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "100 changes detected"}
{"timestamp": "2025-10-02T12:01:24.137425+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:02:00.863921+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/", "status": 404, "duration": 0.001}
{"timestamp": "2025-10-02T12:02:00.863921+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/", "status": 404, "duration": 0.001}
{"timestamp": "2025-10-02T12:02:01.344807+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/", "status": 404, "duration": 0.0}
{"timestamp": "2025-10-02T12:02:01.345815+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/", "status": 404, "duration": 0.0}
{"timestamp": "2025-10-02T12:02:01.568079+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/favicon.ico", "status": 404, "duration": 0.0}
{"timestamp": "2025-10-02T12:02:01.568079+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/favicon.ico", "status": 404, "duration": 0.0}
{"timestamp": "2025-10-02T12:02:05.624177+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/docs", "status": 200, "duration": 0.001}
{"timestamp": "2025-10-02T12:02:05.624177+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/docs", "status": 200, "duration": 0.001}
{"timestamp": "2025-10-02T12:02:06.821233+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/openapi.json", "status": 200, "duration": 0.059}
{"timestamp": "2025-10-02T12:02:06.821233+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/openapi.json", "status": 200, "duration": 0.059}
{"timestamp": "2025-10-02T12:02:06.868706+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "4 changes detected"}
{"timestamp": "2025-10-02T12:02:34.421091+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "53 changes detected"}
{"timestamp": "2025-10-02T12:02:35.185572+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "71 changes detected"}
{"timestamp": "2025-10-02T12:02:35.552069+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "17 changes detected"}
{"timestamp": "2025-10-02T12:02:40.275823+01:00", "level": "INFO", "logger": "httpx", "message": "HTTP Request: POST https://api.cloudinary.com/v1_1/dpmpvftcw/auto/upload \"HTTP/1.1 200 OK\""}
{"timestamp": "2025-10-02T12:02:40.301582+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "POST", "path": "/v1/file/upload/cloudinary", "status": 200, "duration": 6.474}
{"timestamp": "2025-10-02T12:02:40.301582+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "POST", "path": "/v1/file/upload/cloudinary", "status": 200, "duration": 6.474}
{"timestamp": "2025-10-02T12:03:37.933042+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "4 changes detected"}
{"timestamp": "2025-10-02T12:03:42.103158+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "POST", "path": "/v1/users/", "status": 201, "duration": 4.486}
{"timestamp": "2025-10-02T12:03:42.103158+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "POST", "path": "/v1/users/", "status": 201, "duration": 4.486}
{"timestamp": "2025-10-02T12:04:46.337868+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:04:47.358935+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:04:48.833366+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:04:53.040706+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "6 changes detected"}
{"timestamp": "2025-10-02T12:05:02.183500+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:05:03.212516+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:05:05.335573+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:05:08.621164+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:05:09.628718+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:05:10.695690+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:05:15.731621+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "7 changes detected"}
{"timestamp": "2025-10-02T12:05:22.441234+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:05:24.864147+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:05:26.542503+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:05:28.665952+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "2 changes detected"}
{"timestamp": "2025-10-02T12:05:31.923034+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:05:33.217345+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:05:38.011307+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "6 changes detected"}
{"timestamp": "2025-10-02T12:05:56.942396+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "POST", "path": "/v1/users/login", "status": 200, "duration": 0.529}
{"timestamp": "2025-10-02T12:05:56.943396+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "POST", "path": "/v1/users/login", "status": 200, "duration": 0.529}
{"timestamp": "2025-10-02T12:06:18.163212+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/docs", "status": 200, "duration": 0.001}
{"timestamp": "2025-10-02T12:06:18.163212+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/docs", "status": 200, "duration": 0.001}
{"timestamp": "2025-10-02T12:06:18.507760+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/openapi.json", "status": 200, "duration": 0.12}
{"timestamp": "2025-10-02T12:06:18.508762+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/openapi.json", "status": 200, "duration": 0.12}
{"timestamp": "2025-10-02T12:06:29.579327+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 500, "duration": 0.014, "error": "1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': [{'id': '1', 'first_name': 'string', 'last_name': 'string', 'other_name': 'string', 'email': 'user@example.com', 'phone_number': 'stringstri', 'contact_address': 'string', 'is_active': True, 'is_verified': False, 'is_superuser': False, 'is_staff': False, 'profile_picture': <tortoise.queryset.QuerySet object at 0x000002627FD0EB00>, 'is_deleted': False, 'last_login': '2025-10-02T12:05:56.720350+01:00', 'has_agreed_to_terms': True, 'latitude': 0.0, 'longitude': 0.0, 'device_id': 'string', 'ip_address': '127.0.0.1', 'permission_groups': None, 'created_at': '2025-10-02T12:03:38.076558+01:00', 'updated_at': '2025-10-02T12:05:56.917870+01:00'}]}\n", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 151, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 126, in receive\n    raise EndOfStream from None\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 334, in app\n    content = await serialize_response(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 183, in serialize_response\n    raise ResponseValidationError(\nfastapi.exceptions.ResponseValidationError: 1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': [{'id': '1', 'first_name': 'string', 'last_name': 'string', 'other_name': 'string', 'email': 'user@example.com', 'phone_number': 'stringstri', 'contact_address': 'string', 'is_active': True, 'is_verified': False, 'is_superuser': False, 'is_staff': False, 'profile_picture': <tortoise.queryset.QuerySet object at 0x000002627FD0EB00>, 'is_deleted': False, 'last_login': '2025-10-02T12:05:56.720350+01:00', 'has_agreed_to_terms': True, 'latitude': 0.0, 'longitude': 0.0, 'device_id': 'string', 'ip_address': '127.0.0.1', 'permission_groups': None, 'created_at': '2025-10-02T12:03:38.076558+01:00', 'updated_at': '2025-10-02T12:05:56.917870+01:00'}]}\n\n"}
{"timestamp": "2025-10-02T12:06:29.579327+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 500, "duration": 0.014, "error": "1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': [{'id': '1', 'first_name': 'string', 'last_name': 'string', 'other_name': 'string', 'email': 'user@example.com', 'phone_number': 'stringstri', 'contact_address': 'string', 'is_active': True, 'is_verified': False, 'is_superuser': False, 'is_staff': False, 'profile_picture': <tortoise.queryset.QuerySet object at 0x000002627FD0EB00>, 'is_deleted': False, 'last_login': '2025-10-02T12:05:56.720350+01:00', 'has_agreed_to_terms': True, 'latitude': 0.0, 'longitude': 0.0, 'device_id': 'string', 'ip_address': '127.0.0.1', 'permission_groups': None, 'created_at': '2025-10-02T12:03:38.076558+01:00', 'updated_at': '2025-10-02T12:05:56.917870+01:00'}]}\n", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 151, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 126, in receive\n    raise EndOfStream from None\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 334, in app\n    content = await serialize_response(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 183, in serialize_response\n    raise ResponseValidationError(\nfastapi.exceptions.ResponseValidationError: 1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': [{'id': '1', 'first_name': 'string', 'last_name': 'string', 'other_name': 'string', 'email': 'user@example.com', 'phone_number': 'stringstri', 'contact_address': 'string', 'is_active': True, 'is_verified': False, 'is_superuser': False, 'is_staff': False, 'profile_picture': <tortoise.queryset.QuerySet object at 0x000002627FD0EB00>, 'is_deleted': False, 'last_login': '2025-10-02T12:05:56.720350+01:00', 'has_agreed_to_terms': True, 'latitude': 0.0, 'longitude': 0.0, 'device_id': 'string', 'ip_address': '127.0.0.1', 'permission_groups': None, 'created_at': '2025-10-02T12:03:38.076558+01:00', 'updated_at': '2025-10-02T12:05:56.917870+01:00'}]}\n\n"}
{"timestamp": "2025-10-02T12:06:47.252981+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:06:48.209661+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:06:50.438007+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:06:54.742408+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:06:55.782236+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:06:58.365604+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:07:01.268036+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 500, "duration": 0.16, "error": "[ParamsError('QuerySet indices must be slices.'), TypeError('vars() argument must have __dict__ attribute')]", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 325, in jsonable_encoder\n    data = dict(obj)\n           ^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\tortoise\\queryset.py\", line 547, in __getitem__\n    raise ParamsError(\"QuerySet indices must be slices.\")\ntortoise.exceptions.ParamsError: QuerySet indices must be slices.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 330, in jsonable_encoder\n    data = vars(obj)\n           ^^^^^^^^^\nTypeError: vars() argument must have __dict__ attribute\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 334, in app\n    content = await serialize_response(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 208, in serialize_response\n    return jsonable_encoder(response_content)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 304, in jsonable_encoder\n    jsonable_encoder(\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 290, in jsonable_encoder\n    encoded_value = jsonable_encoder(\n                    ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 333, in jsonable_encoder\n    raise ValueError(errors) from e\nValueError: [ParamsError('QuerySet indices must be slices.'), TypeError('vars() argument must have __dict__ attribute')]\n"}
{"timestamp": "2025-10-02T12:07:01.269036+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 500, "duration": 0.16, "error": "[ParamsError('QuerySet indices must be slices.'), TypeError('vars() argument must have __dict__ attribute')]", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 325, in jsonable_encoder\n    data = dict(obj)\n           ^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\tortoise\\queryset.py\", line 547, in __getitem__\n    raise ParamsError(\"QuerySet indices must be slices.\")\ntortoise.exceptions.ParamsError: QuerySet indices must be slices.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 330, in jsonable_encoder\n    data = vars(obj)\n           ^^^^^^^^^\nTypeError: vars() argument must have __dict__ attribute\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 334, in app\n    content = await serialize_response(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 208, in serialize_response\n    return jsonable_encoder(response_content)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 304, in jsonable_encoder\n    jsonable_encoder(\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 290, in jsonable_encoder\n    encoded_value = jsonable_encoder(\n                    ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 333, in jsonable_encoder\n    raise ValueError(errors) from e\nValueError: [ParamsError('QuerySet indices must be slices.'), TypeError('vars() argument must have __dict__ attribute')]\n"}
{"timestamp": "2025-10-02T12:42:27.829565+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:42:28.747948+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:42:32.283988+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:42:34.534784+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:42:38.031551+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "7 changes detected"}
{"timestamp": "2025-10-02T12:42:39.667188+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:42:44.231641+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "6 changes detected"}
{"timestamp": "2025-10-02T12:42:46.789679+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "6 changes detected"}
{"timestamp": "2025-10-02T12:42:50.220016+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:43:03.015039+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 200, "duration": 0.148}
{"timestamp": "2025-10-02T12:43:03.016044+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 200, "duration": 0.148}
{"timestamp": "2025-10-02T12:43:27.688123+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:43:28.679694+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "2 changes detected"}
{"timestamp": "2025-10-02T12:43:31.502114+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:45:03.976331+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:45:04.913778+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:45:07.756347+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:45:10.599640+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:45:11.644536+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:45:14.281200+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:45:36.766748+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 200, "duration": 0.134}
{"timestamp": "2025-10-02T12:45:36.766748+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 200, "duration": 0.134}
{"timestamp": "2025-10-02T12:47:02.906563+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:47:03.868422+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:47:06.299006+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:47:11.946489+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:47:12.841330+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:47:14.950370+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:47:33.244350+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:47:34.196460+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:47:36.270921+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:47:39.812746+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:47:42.203502+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:47:44.080868+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:47:45.939738+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:47:49.225707+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:47:51.557273+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:48:00.055172+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:48:01.041264+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:48:03.222544+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:48:07.974600+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/docs", "status": 200, "duration": 0.001}
{"timestamp": "2025-10-02T12:48:07.974600+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/docs", "status": 200, "duration": 0.001}
{"timestamp": "2025-10-02T12:48:08.176358+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/openapi.json", "status": 200, "duration": 0.048}
{"timestamp": "2025-10-02T12:48:08.176358+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/openapi.json", "status": 200, "duration": 0.048}
{"timestamp": "2025-10-02T12:48:18.634632+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 500, "duration": 0.118, "error": "1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': [{'id': '1', 'first_name': 'string', 'last_name': 'string', 'other_name': 'string', 'email': 'user@example.com', 'phone_number': 'stringstri', 'contact_address': 'string', 'is_active': True, 'is_verified': False, 'is_superuser': False, 'is_staff': False, 'profile_picture': 'https://res.cloudinary.com/dpmpvftcw/image/upload/v1759402959/mlt5wbpiizjcvhvhqdsq.gif', 'is_deleted': False, 'last_login': '2025-10-02T12:05:56.720350+01:00', 'has_agreed_to_terms': True, 'latitude': 0.0, 'longitude': 0.0, 'device_id': 'string', 'ip_address': '127.0.0.1', 'permission_groups': None, 'created_at': '2025-10-02T12:03:38.076558+01:00', 'updated_at': '2025-10-02T12:05:56.917870+01:00'}]}\n", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 151, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 126, in receive\n    raise EndOfStream from None\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 334, in app\n    content = await serialize_response(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 183, in serialize_response\n    raise ResponseValidationError(\nfastapi.exceptions.ResponseValidationError: 1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': [{'id': '1', 'first_name': 'string', 'last_name': 'string', 'other_name': 'string', 'email': 'user@example.com', 'phone_number': 'stringstri', 'contact_address': 'string', 'is_active': True, 'is_verified': False, 'is_superuser': False, 'is_staff': False, 'profile_picture': 'https://res.cloudinary.com/dpmpvftcw/image/upload/v1759402959/mlt5wbpiizjcvhvhqdsq.gif', 'is_deleted': False, 'last_login': '2025-10-02T12:05:56.720350+01:00', 'has_agreed_to_terms': True, 'latitude': 0.0, 'longitude': 0.0, 'device_id': 'string', 'ip_address': '127.0.0.1', 'permission_groups': None, 'created_at': '2025-10-02T12:03:38.076558+01:00', 'updated_at': '2025-10-02T12:05:56.917870+01:00'}]}\n\n"}
{"timestamp": "2025-10-02T12:48:18.634632+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 500, "duration": 0.118, "error": "1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': [{'id': '1', 'first_name': 'string', 'last_name': 'string', 'other_name': 'string', 'email': 'user@example.com', 'phone_number': 'stringstri', 'contact_address': 'string', 'is_active': True, 'is_verified': False, 'is_superuser': False, 'is_staff': False, 'profile_picture': 'https://res.cloudinary.com/dpmpvftcw/image/upload/v1759402959/mlt5wbpiizjcvhvhqdsq.gif', 'is_deleted': False, 'last_login': '2025-10-02T12:05:56.720350+01:00', 'has_agreed_to_terms': True, 'latitude': 0.0, 'longitude': 0.0, 'device_id': 'string', 'ip_address': '127.0.0.1', 'permission_groups': None, 'created_at': '2025-10-02T12:03:38.076558+01:00', 'updated_at': '2025-10-02T12:05:56.917870+01:00'}]}\n", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 151, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 126, in receive\n    raise EndOfStream from None\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 334, in app\n    content = await serialize_response(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 183, in serialize_response\n    raise ResponseValidationError(\nfastapi.exceptions.ResponseValidationError: 1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': [{'id': '1', 'first_name': 'string', 'last_name': 'string', 'other_name': 'string', 'email': 'user@example.com', 'phone_number': 'stringstri', 'contact_address': 'string', 'is_active': True, 'is_verified': False, 'is_superuser': False, 'is_staff': False, 'profile_picture': 'https://res.cloudinary.com/dpmpvftcw/image/upload/v1759402959/mlt5wbpiizjcvhvhqdsq.gif', 'is_deleted': False, 'last_login': '2025-10-02T12:05:56.720350+01:00', 'has_agreed_to_terms': True, 'latitude': 0.0, 'longitude': 0.0, 'device_id': 'string', 'ip_address': '127.0.0.1', 'permission_groups': None, 'created_at': '2025-10-02T12:03:38.076558+01:00', 'updated_at': '2025-10-02T12:05:56.917870+01:00'}]}\n\n"}
{"timestamp": "2025-10-02T12:48:28.650408+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:48:29.567902+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:48:30.639103+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:48:35.277606+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "6 changes detected"}
{"timestamp": "2025-10-02T12:48:45.512704+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 500, "duration": 0.14, "error": "1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': [{'id': '1', 'first_name': 'string', 'last_name': 'string', 'other_name': 'string', 'email': 'user@example.com', 'phone_number': 'stringstri', 'contact_address': 'string', 'is_active': True, 'is_verified': False, 'is_superuser': False, 'is_staff': False, 'profile_picture': 'https://res.cloudinary.com/dpmpvftcw/image/upload/v1759402959/mlt5wbpiizjcvhvhqdsq.gif', 'is_deleted': False, 'last_login': '2025-10-02T12:05:56.720350+01:00', 'has_agreed_to_terms': True, 'latitude': 0.0, 'longitude': 0.0, 'device_id': 'string', 'ip_address': '127.0.0.1', 'permission_groups': None, 'created_at': '2025-10-02T12:03:38.076558+01:00', 'updated_at': '2025-10-02T12:05:56.917870+01:00'}]}\n", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 151, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 126, in receive\n    raise EndOfStream from None\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 334, in app\n    content = await serialize_response(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 183, in serialize_response\n    raise ResponseValidationError(\nfastapi.exceptions.ResponseValidationError: 1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': [{'id': '1', 'first_name': 'string', 'last_name': 'string', 'other_name': 'string', 'email': 'user@example.com', 'phone_number': 'stringstri', 'contact_address': 'string', 'is_active': True, 'is_verified': False, 'is_superuser': False, 'is_staff': False, 'profile_picture': 'https://res.cloudinary.com/dpmpvftcw/image/upload/v1759402959/mlt5wbpiizjcvhvhqdsq.gif', 'is_deleted': False, 'last_login': '2025-10-02T12:05:56.720350+01:00', 'has_agreed_to_terms': True, 'latitude': 0.0, 'longitude': 0.0, 'device_id': 'string', 'ip_address': '127.0.0.1', 'permission_groups': None, 'created_at': '2025-10-02T12:03:38.076558+01:00', 'updated_at': '2025-10-02T12:05:56.917870+01:00'}]}\n\n"}
{"timestamp": "2025-10-02T12:48:45.512704+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 500, "duration": 0.14, "error": "1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': [{'id': '1', 'first_name': 'string', 'last_name': 'string', 'other_name': 'string', 'email': 'user@example.com', 'phone_number': 'stringstri', 'contact_address': 'string', 'is_active': True, 'is_verified': False, 'is_superuser': False, 'is_staff': False, 'profile_picture': 'https://res.cloudinary.com/dpmpvftcw/image/upload/v1759402959/mlt5wbpiizjcvhvhqdsq.gif', 'is_deleted': False, 'last_login': '2025-10-02T12:05:56.720350+01:00', 'has_agreed_to_terms': True, 'latitude': 0.0, 'longitude': 0.0, 'device_id': 'string', 'ip_address': '127.0.0.1', 'permission_groups': None, 'created_at': '2025-10-02T12:03:38.076558+01:00', 'updated_at': '2025-10-02T12:05:56.917870+01:00'}]}\n", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 151, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 126, in receive\n    raise EndOfStream from None\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 334, in app\n    content = await serialize_response(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 183, in serialize_response\n    raise ResponseValidationError(\nfastapi.exceptions.ResponseValidationError: 1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': [{'id': '1', 'first_name': 'string', 'last_name': 'string', 'other_name': 'string', 'email': 'user@example.com', 'phone_number': 'stringstri', 'contact_address': 'string', 'is_active': True, 'is_verified': False, 'is_superuser': False, 'is_staff': False, 'profile_picture': 'https://res.cloudinary.com/dpmpvftcw/image/upload/v1759402959/mlt5wbpiizjcvhvhqdsq.gif', 'is_deleted': False, 'last_login': '2025-10-02T12:05:56.720350+01:00', 'has_agreed_to_terms': True, 'latitude': 0.0, 'longitude': 0.0, 'device_id': 'string', 'ip_address': '127.0.0.1', 'permission_groups': None, 'created_at': '2025-10-02T12:03:38.076558+01:00', 'updated_at': '2025-10-02T12:05:56.917870+01:00'}]}\n\n"}
{"timestamp": "2025-10-02T12:49:07.572835+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:49:08.520109+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:49:10.693302+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:49:11.057786+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:49:13.566128+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:49:19.215454+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 500, "duration": 0.173, "error": "BaseModel.__init__() takes 1 positional argument but 2 were given", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 151, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 126, in receive\n    raise EndOfStream from None\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 345, in app\n    response = actual_response_class(content, **response_args)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: BaseModel.__init__() takes 1 positional argument but 2 were given\n"}
{"timestamp": "2025-10-02T12:49:19.216463+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 500, "duration": 0.173, "error": "BaseModel.__init__() takes 1 positional argument but 2 were given", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 151, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 126, in receive\n    raise EndOfStream from None\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 345, in app\n    response = actual_response_class(content, **response_args)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: BaseModel.__init__() takes 1 positional argument but 2 were given\n"}
{"timestamp": "2025-10-02T12:49:56.742111+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:49:57.745737+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:50:00.021660+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:50:00.477717+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:50:01.708549+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:50:05.632140+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:50:08.070107+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:50:10.347243+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:50:11.779542+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:50:16.440848+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "6 changes detected"}
{"timestamp": "2025-10-02T12:50:23.231339+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 500, "duration": 0.146, "error": "3 validation errors:\n  {'type': 'uuid_parsing', 'loc': ('response', 0, 'id'), 'msg': 'Input should be a valid UUID, invalid length: expected length 32 for simple format, found 1', 'input': '1', 'ctx': {'error': 'invalid length: expected length 32 for simple format, found 1'}}\n  {'type': 'string_type', 'loc': ('response', 0, 'latitude'), 'msg': 'Input should be a valid string', 'input': 0.0}\n  {'type': 'string_type', 'loc': ('response', 0, 'longitude'), 'msg': 'Input should be a valid string', 'input': 0.0}\n", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 151, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 126, in receive\n    raise EndOfStream from None\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 334, in app\n    content = await serialize_response(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 183, in serialize_response\n    raise ResponseValidationError(\nfastapi.exceptions.ResponseValidationError: 3 validation errors:\n  {'type': 'uuid_parsing', 'loc': ('response', 0, 'id'), 'msg': 'Input should be a valid UUID, invalid length: expected length 32 for simple format, found 1', 'input': '1', 'ctx': {'error': 'invalid length: expected length 32 for simple format, found 1'}}\n  {'type': 'string_type', 'loc': ('response', 0, 'latitude'), 'msg': 'Input should be a valid string', 'input': 0.0}\n  {'type': 'string_type', 'loc': ('response', 0, 'longitude'), 'msg': 'Input should be a valid string', 'input': 0.0}\n\n"}
{"timestamp": "2025-10-02T12:50:23.231339+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 500, "duration": 0.146, "error": "3 validation errors:\n  {'type': 'uuid_parsing', 'loc': ('response', 0, 'id'), 'msg': 'Input should be a valid UUID, invalid length: expected length 32 for simple format, found 1', 'input': '1', 'ctx': {'error': 'invalid length: expected length 32 for simple format, found 1'}}\n  {'type': 'string_type', 'loc': ('response', 0, 'latitude'), 'msg': 'Input should be a valid string', 'input': 0.0}\n  {'type': 'string_type', 'loc': ('response', 0, 'longitude'), 'msg': 'Input should be a valid string', 'input': 0.0}\n", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 151, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 126, in receive\n    raise EndOfStream from None\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 334, in app\n    content = await serialize_response(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 183, in serialize_response\n    raise ResponseValidationError(\nfastapi.exceptions.ResponseValidationError: 3 validation errors:\n  {'type': 'uuid_parsing', 'loc': ('response', 0, 'id'), 'msg': 'Input should be a valid UUID, invalid length: expected length 32 for simple format, found 1', 'input': '1', 'ctx': {'error': 'invalid length: expected length 32 for simple format, found 1'}}\n  {'type': 'string_type', 'loc': ('response', 0, 'latitude'), 'msg': 'Input should be a valid string', 'input': 0.0}\n  {'type': 'string_type', 'loc': ('response', 0, 'longitude'), 'msg': 'Input should be a valid string', 'input': 0.0}\n\n"}
{"timestamp": "2025-10-02T12:50:55.611726+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:50:56.618265+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:50:58.641045+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:51:05.552890+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:51:06.474884+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:51:08.195313+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:51:12.242960+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "6 changes detected"}
{"timestamp": "2025-10-02T12:51:16.719224+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:51:17.933953+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:51:22.084417+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:51:24.827496+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:52:11.258031+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:52:12.225296+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:52:14.554079+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:52:18.879176+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 200, "duration": 0.138}
{"timestamp": "2025-10-02T12:52:18.879176+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 200, "duration": 0.138}
{"timestamp": "2025-10-02T12:54:13.788195+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:54:14.846626+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:54:17.071498+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:56:13.573047+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:56:14.501128+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:56:29.517960+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:56:31.695074+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:56:35.491699+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "6 changes detected"}
{"timestamp": "2025-10-02T12:56:42.146327+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:56:43.181859+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:56:45.657335+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:56:51.280939+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:56:52.200156+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:56:54.479932+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:56:55.648237+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:56:58.021493+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:57:00.546985+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:57:21.883891+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/docs", "status": 200, "duration": 0.001}
{"timestamp": "2025-10-02T12:57:21.883891+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/docs", "status": 200, "duration": 0.001}
{"timestamp": "2025-10-02T12:57:22.041008+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/openapi.json", "status": 200, "duration": 0.045}
{"timestamp": "2025-10-02T12:57:22.041008+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/openapi.json", "status": 200, "duration": 0.045}
{"timestamp": "2025-10-02T12:57:49.776178+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:57:50.757054+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:57:52.977575+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:57:53.583838+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:57:55.397704+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:57:57.057662+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:57:58.730963+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:57:59.717941+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:58:00.076121+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:58:02.598183+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:58:15.317223+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:58:16.256979+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:58:18.601136+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T12:58:23.574676+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/docs", "status": 200, "duration": 0.001}
{"timestamp": "2025-10-02T12:58:23.574676+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/docs", "status": 200, "duration": 0.001}
{"timestamp": "2025-10-02T12:58:23.745652+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/openapi.json", "status": 200, "duration": 0.08}
{"timestamp": "2025-10-02T12:58:23.745652+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/openapi.json", "status": 200, "duration": 0.08}
{"timestamp": "2025-10-02T12:58:32.495354+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 500, "duration": 0.001, "error": "type object 'UserService' has no attribute 'all'", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 151, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 111, in receive\n    return self.receive_nowait()\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 104, in receive_nowait\n    raise EndOfStream\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 308, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 219, in run_endpoint_function\n    return await dependant.call(**values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\apps\\auth\\user\\routes.py\", line 20, in get_all\n    return await UserService.all(is_staff, is_admin, is_verified, limit, offset)\n                 ^^^^^^^^^^^^^^^\nAttributeError: type object 'UserService' has no attribute 'all'\n"}
{"timestamp": "2025-10-02T12:58:32.496355+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 500, "duration": 0.001, "error": "type object 'UserService' has no attribute 'all'", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 151, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 111, in receive\n    return self.receive_nowait()\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 104, in receive_nowait\n    raise EndOfStream\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 308, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 219, in run_endpoint_function\n    return await dependant.call(**values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\apps\\auth\\user\\routes.py\", line 20, in get_all\n    return await UserService.all(is_staff, is_admin, is_verified, limit, offset)\n                 ^^^^^^^^^^^^^^^\nAttributeError: type object 'UserService' has no attribute 'all'\n"}
{"timestamp": "2025-10-02T12:59:02.963543+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:59:04.021784+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:59:05.995096+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:59:09.368963+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T12:59:11.972448+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T13:00:26.728119+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/docs", "status": 200, "duration": 0.002}
{"timestamp": "2025-10-02T13:00:26.728119+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/docs", "status": 200, "duration": 0.002}
{"timestamp": "2025-10-02T13:00:26.911294+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/openapi.json", "status": 200, "duration": 0.083}
{"timestamp": "2025-10-02T13:00:26.912287+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/openapi.json", "status": 200, "duration": 0.083}
{"timestamp": "2025-10-02T13:00:31.821361+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 500, "duration": 0.195, "error": "list.count() takes exactly one argument (0 given)", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 151, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 126, in receive\n    raise EndOfStream from None\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 308, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 219, in run_endpoint_function\n    return await dependant.call(**values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\apps\\auth\\user\\routes.py\", line 20, in get_all\n    return await UserService.all(is_staff, is_admin, is_verified, limit, offset)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\apps\\auth\\user\\services.py\", line 113, in all\n    total_count = await query.count()  # For frontend to know total\n                        ^^^^^^^^^^^^^\nTypeError: list.count() takes exactly one argument (0 given)\n"}
{"timestamp": "2025-10-02T13:00:31.822656+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 500, "duration": 0.195, "error": "list.count() takes exactly one argument (0 given)", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 151, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 126, in receive\n    raise EndOfStream from None\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 308, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 219, in run_endpoint_function\n    return await dependant.call(**values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\apps\\auth\\user\\routes.py\", line 20, in get_all\n    return await UserService.all(is_staff, is_admin, is_verified, limit, offset)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\apps\\auth\\user\\services.py\", line 113, in all\n    total_count = await query.count()  # For frontend to know total\n                        ^^^^^^^^^^^^^\nTypeError: list.count() takes exactly one argument (0 given)\n"}
{"timestamp": "2025-10-02T13:02:30.231639+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:02:31.315841+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:02:33.669815+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T13:02:35.142447+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:02:37.184794+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:02:39.458968+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T13:02:43.627428+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:02:44.556568+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:02:46.728405+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T13:02:53.792407+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 200, "duration": 0.179}
{"timestamp": "2025-10-02T13:02:53.792407+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 200, "duration": 0.179}
{"timestamp": "2025-10-02T13:04:04.357580+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 200, "duration": 0.009}
{"timestamp": "2025-10-02T13:04:04.357580+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/v1/users/", "status": 200, "duration": 0.009}
{"timestamp": "2025-10-02T13:05:27.449146+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T13:05:27.808407+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:05:29.779502+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:05:30.772718+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:05:31.382473+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:05:33.851289+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:05:35.597585+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:05:37.468080+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:05:40.548188+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:05:42.794910+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:05:46.965376+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "6 changes detected"}
{"timestamp": "2025-10-02T13:05:54.259196+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:05:55.291429+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:05:56.515128+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:05:58.889660+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:06:04.093981+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "7 changes detected"}
{"timestamp": "2025-10-02T13:06:15.885581+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:06:17.421728+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:06:22.133981+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "7 changes detected"}
{"timestamp": "2025-10-02T13:06:23.143083+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:06:26.919245+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:06:32.442779+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "7 changes detected"}
{"timestamp": "2025-10-02T13:06:35.839597+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "5 changes detected"}
{"timestamp": "2025-10-02T13:07:14.490997+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "POST", "path": "/v1/users/", "status": 500, "duration": 0.024, "error": "badly formed hexadecimal UUID string", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 151, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 126, in receive\n    raise EndOfStream from None\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 93, in __call__\n    await self.simple_response(scope, receive, send, request_headers=headers)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 144, in simple_response\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 308, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 219, in run_endpoint_function\n    return await dependant.call(**values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\apps\\auth\\user\\routes.py\", line 24, in create_user\n    return await UserService.create_user(dto=dto, request=request, response=response)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\apps\\auth\\user\\services.py\", line 36, in create_user\n    user = await cls.model.create(**dict(dto))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\tortoise\\models.py\", line 1207, in create\n    instance = cls(**kwargs)\n               ^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\tortoise\\models.py\", line 698, in __init__\n    for key in meta.fields.difference(self._set_kwargs(kwargs)):\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\tortoise\\models.py\", line 736, in _set_kwargs\n    setattr(self, key, field_object.to_python_value(value))\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\tortoise\\fields\\data.py\", line 651, in to_python_value\n    return UUID(value)\n           ^^^^^^^^^^^\n  File \"C:\\Users\\PC\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\uuid.py\", line 178, in __init__\n    raise ValueError('badly formed hexadecimal UUID string')\nValueError: badly formed hexadecimal UUID string\n"}
{"timestamp": "2025-10-02T13:07:14.490997+01:00", "level": "ERROR", "logger": "bank-backend", "message": "request_failed", "ip": "127.0.0.1", "method": "POST", "path": "/v1/users/", "status": 500, "duration": 0.024, "error": "badly formed hexadecimal UUID string", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 151, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\anyio\\streams\\memory.py\", line 126, in receive\n    raise EndOfStream from None\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\dependencies\\middlewares\\logmiddleware.py\", line 20, in dispatch\n    response: Response = await call_next(request)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 159, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 93, in __call__\n    await self.simple_response(scope, receive, send, request_headers=headers)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 144, in simple_response\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 29, in __call__\n    await responder(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 130, in __call__\n    await super().__call__(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\gzip.py\", line 46, in __call__\n    await self.app(scope, receive, self.send_with_compression)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\starlette\\routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 308, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\fastapi\\routing.py\", line 219, in run_endpoint_function\n    return await dependant.call(**values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\apps\\auth\\user\\routes.py\", line 24, in create_user\n    return await UserService.create_user(dto=dto, request=request, response=response)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\src\\apps\\auth\\user\\services.py\", line 36, in create_user\n    user = await cls.model.create(**dict(dto))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\tortoise\\models.py\", line 1207, in create\n    instance = cls(**kwargs)\n               ^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\tortoise\\models.py\", line 698, in __init__\n    for key in meta.fields.difference(self._set_kwargs(kwargs)):\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\tortoise\\models.py\", line 736, in _set_kwargs\n    setattr(self, key, field_object.to_python_value(value))\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\FHAMB-Backend-2\\.venv\\Lib\\site-packages\\tortoise\\fields\\data.py\", line 651, in to_python_value\n    return UUID(value)\n           ^^^^^^^^^^^\n  File \"C:\\Users\\PC\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\uuid.py\", line 178, in __init__\n    raise ValueError('badly formed hexadecimal UUID string')\nValueError: badly formed hexadecimal UUID string\n"}
{"timestamp": "2025-10-02T13:09:02.146036+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "POST", "path": "/v1/users/", "status": 201, "duration": 0.374}
{"timestamp": "2025-10-02T13:09:02.146036+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "POST", "path": "/v1/users/", "status": 201, "duration": 0.374}
{"timestamp": "2025-10-02T13:09:14.073478+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/v1/subscriber/", "status": 200, "duration": 0.112}
{"timestamp": "2025-10-02T13:09:14.073478+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/v1/subscriber/", "status": 200, "duration": 0.112}
{"timestamp": "2025-10-02T13:10:14.658602+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/v1/permissions/", "status": 403, "duration": 0.001}
{"timestamp": "2025-10-02T13:10:14.658602+01:00", "level": "INFO", "logger": "bank-backend", "message": "request_success", "ip": "127.0.0.1", "method": "GET", "path": "/v1/permissions/", "status": 403, "duration": 0.001}
{"timestamp": "2025-10-02T13:29:59.435696+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:31:31.575301+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:31:34.108315+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:31:38.003818+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
{"timestamp": "2025-10-02T13:31:41.701466+01:00", "level": "INFO", "logger": "watchfiles.main", "message": "1 change detected"}
